### PR TITLE
Nj fix local storage

### LINKED ISSUE #44: fix local storage functionality
AC:

- A token should only be added to the datalist if the user has added items to the list associated with it.

### PR DESCRIPTION
**Pull request by artsycoder533**
_For an example of how to fill this template out, [see this Pull Request](https://github.com/the-collab-lab/tcl-3-smart-shopping-list/pull/44)._ 

## Description

A token is now only added to the datalist when a user has added an item to that list, that way only tokens that a user will be able to view will show in the datalist.  If a user is adding items to a list that already exists that token will not be added to the datalist more than once. Once a new token is created, the user is redirected to the additem view instead of the list view.  If a user selects a valid list form the share token input, they are redirected to the list view, otherwise they see an error. I also changed the share token input type to search to be more semantic as well as allow the user to easily clear the input field.

## Related Issue

closes #44 

## Acceptance Criteria

AC:

A token should only be added to the datalist if the user has added items to the list associated with it.

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|  ✓ | :bug: Bug fix              |
|   | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

### Demo Video
[See Demo Video on YouTube (right click & open in a new tab)](https://youtu.be/CpKd7OkhTIk)

## Testing Steps / QA Criteria

checkout `nj-fix-local-storage`

1. clear your local storage (keep it open so you can see whats happening)
2. Create a new token, you should be redirected to the add item page.
3. the token value in local storage should now have a value
4. add an item to the list
5. go back to the home view
6. clear out the share token input field
7. click the input field, the `datalist` should appear
8. the token that was just displayed in the share token field should be displayed in the `datalist`
9. select this token and click `join an existing list`, you should be taken to the list view and see the item you added
10. add another item to this list, the token list should not have any duplicate tokens
11. go back to the home page
12. create another token and add at least one item to it
13. go back to the home page
14. clear the `share token` input field
15. click on the input field to see the `datalist`, there should now be two tokens in the datalist
16. type your name in the share token field and click `join an existing list`
17. you should see an error that says ```This token does not match an existing shopping list. Please check your input and try again.```
18. clear the `share token` input field again, dont type anything and press `join an existing list`, you should see an error that says ```Token cannot be blank!```
19. create another token, but this time do not add an item
20. go back to the home page
21. Make note of the token value in the `share token page```
22. clear this value and click on the input field.
23. You should `NOT` see the token value you just created in the `datalist`

### CODE REVIEW

**Review by sparsell — APPROVED** [review]
All tests pass as directed. Really good instructions.  

Really good error messages and the 'x' to clear the Share Token input form works well too if you are going to be adding someone else's list. 

Great work - makes the app function much better.

File: src/App.js [hunk 1]
```diff
@@ -13,6 +13,22 @@ function App() {
     JSON.parse(localStorage.getItem('tokenList')) || [],
   );
 
+  // add token to local storage
+  const addTokenToLocalStorage = (token) => {
```
Comment (lindseyindev) [inline src/App.js:17]: very clear functions, I know what they're doing just from the title

I keep trying to picture what the stringify and parse are doing -- are they turning the whole array into a string or each item in the array to a string? And was there a bug happening that directed you to this solution?

File: src/App.js [hunk 2]
```diff
@@ -23,15 +39,24 @@ function App() {
...
           path="/list"
           element={<List token={activeToken} tokenList={tokenList} />}
         />
-        <Route path="/additem" element={<AddItem token={activeToken} />} />
+        <Route
+          path="/additem"
+          element={
+            <AddItem
+              token={activeToken}
+              addTokenToLocalStorage={addTokenToLocalStorage}
```
Comment (lindseyindev) [inline src/App.js:55]: again incredibly clear and clean naming of variables

File: src/components/Home/JoinList.jsx [hunk 3]
```diff
@@ -18,7 +18,7 @@ const JoinList = ({
         <label htmlFor="share-token">Share Token:</label>
         <input
           id="share-token"
-          type="text"
+          type="search"
```
Comment (lindseyindev) [inline src/components/Home/JoinList.jsx:21]: I did not know this causes the built-in clear input button! That's awesome!

Comment (lindseyindev) [reply src/components/Home/JoinList.jsx:21]: I know this is previous functionality too but the <datalist> element is also something I haven't seen before and I think it's a great way to accomplish this functionality instead of building a separate selector and you can combine it with the input box all in one place

**Review by lindseyindev — APPROVED** [review]
Great PR!!! BTW the youtube video was private so I couldn't view it but the PR was written so clearly with testing steps which helped me walk through the code changes. The refactoring works SO WELL! Good to merge!

**Review by k-schrattenholzer — APPROVED** [review]
I was able to follow the testing steps without issue - this looks great! 
The error handling feels clear for the user, and the flow through the app makes sense.
